"""3Dconnexion C658 Report 0x10 Linux SDK."""

from .hid_descriptor import (
    HidDescriptorError,
    feature_report_wire_lengths,
    input_report_wire_lengths,
)
from .linux_hidraw import (
    HidrawDevice,
    HidrawInfo,
    discover_receiver_c658_handles,
    discover_report03_inputs,
    discover_wired_c658,
    enumerate_hidraw,
    validate_report10_target,
)
from .report10 import (
    BLOB_LENGTH,
    BUTTON_COUNT,
    REPORT_ID,
    WIRE_LENGTH,
    ButtonMapping,
    DirectAction,
    InspectedButton,
    InspectedReport10,
    LiftDetection,
    PollingRate,
    Report10Config,
    Report10Error,
    WheelMode,
    encode_dpi,
    inspect_wire_report,
)
from .report03 import (
    REPORT03_ID,
    REPORT03_MASKS,
    Report03Error,
    Report03Frame,
    Report03Reader,
    parse_report03,
)
from .receiver import (
    PAIR_START,
    PAIR_STOP,
    UNPAIR_SUBCOMMAND,
    ReceiverSlot,
    build_unpair_packet,
    discover_receiver_management,
    newly_occupied_slots,
    read_receiver_slots,
    set_pairing_mode,
    unpair_slot,
    validate_receiver_management,
)
from .send_cache import CacheSendResult, Report10SendCache

__all__ = [
    "BLOB_LENGTH",
    "BUTTON_COUNT",
    "REPORT_ID",
    "WIRE_LENGTH",
    "ButtonMapping",
    "CacheSendResult",
    "DirectAction",
    "HidDescriptorError",
    "HidrawDevice",
    "HidrawInfo",
    "InspectedButton",
    "InspectedReport10",
    "LiftDetection",
    "PollingRate",
    "PAIR_START",
    "PAIR_STOP",
    "UNPAIR_SUBCOMMAND",
    "REPORT03_ID",
    "REPORT03_MASKS",
    "ReceiverSlot",
    "build_unpair_packet",
    "Report03Error",
    "Report03Frame",
    "Report03Reader",
    "Report10Config",
    "Report10Error",
    "Report10SendCache",
    "WheelMode",
    "discover_receiver_c658_handles",
    "discover_report03_inputs",
    "discover_receiver_management",
    "discover_wired_c658",
    "encode_dpi",
    "enumerate_hidraw",
    "feature_report_wire_lengths",
    "input_report_wire_lengths",
    "inspect_wire_report",
    "newly_occupied_slots",
    "parse_report03",
    "read_receiver_slots",
    "set_pairing_mode",
    "unpair_slot",
    "validate_report10_target",
    "validate_receiver_management",
]
